//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYRIAM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlateContours_PresentDay_Matthews2016 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlateContours_PresentDay_Matthews2016() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MYRIAM.Properties.PlateContours_PresentDay_Matthews2016", typeof(PlateContours_PresentDay_Matthews2016).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///180.0 -67.37
        ///180.0 -90.0
        ///-180.0 -90.0
        ///-180.0 -67.37
        ///-177.253 -66.293
        ///-177.74 -65.808
        ///-177.74 -65.808
        ///-177.072 -65.607
        ///-175.729 -65.183
        ///-175.07 -65.505
        ///-174.418 -65.835
        ///-173.709 -65.506
        ///-172.517 -64.978
        ///-171.3 -64.356
        ///-170.043 -64.859
        ///-169.839 -64.764
        ///-169.109 -64.245
        ///-168.379 -63.73
        ///-167.513 -63.106
        ///-166.608 -62.49
        ///-166.199 -62.606
        ///-165.149 -63.007
        ///-163.921 -63.467
        ///-163.001 -62.967
        ///-162.061 -62.394
        ///-161.338 -62.614
        ///-160.43 -62.923
        ///-159.888 -62.595
        ///-158.703 -63.004
        ///-158 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ANT_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("ANT_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///43.7 11.9
        ///43.5 12.2
        ///42.5 13.2
        ///41.6 14.3
        ///40.5 16.0
        ///39.4 18.1
        ///38.5 19.8
        ///37.2 22.0
        ///36.2 23.8
        ///35.3 25.3
        ///34.6 26.6
        ///34.2 27.1
        ///34.2 27.1
        ///34.2 27.9
        ///34.5 28.4
        ///34.7 29.0
        ///34.9 29.5
        ///34.9 30.0
        ///34.9 30.8
        ///35.0 31.3
        ///35.0 32.1
        ///35.2 32.9
        ///35.5 34.0
        ///35.7 34.9
        ///35.8 35.7
        ///35.6 35.9
        ///35.873 36.355
        ///35.873 36.355
        ///36.404 36.003
        ///37.179 36.633
        ///37.94 37.138
        ///38.92 37.293
        ///39.681 37.311
        ///41.157 37.059
        ///42.536 36.689
        ///43.756 36.276
        ///45.401 35.523
        ///47.911 33.625
        ///50.851 32.135
        ///52.485 30.84
        ///54.319 29 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ARB_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("ARB_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///180.0 -17.5541
        ///180.0 -37.4573
        ///179.004 -39.2076
        ///178.95 -39.68
        ///178.79 -40.09
        ///178.56 -40.42
        ///178.29 -40.8
        ///178.02 -41.19
        ///177.6 -41.5
        ///177.12 -41.66
        ///176.68 -41.75
        ///176.08 -41.91
        ///175.5 -42.06
        ///174.98 -42.12
        ///174.31 -42.2
        ///173.72 -42.29
        ///173.13 -42.39
        ///172.6 -42.48
        ///171.86 -42.61
        ///171.27 -42.73
        ///170.6156 -42.7397
        ///170.6156 -42.7397
        ///170.488 -43.0749
        ///170.11 -43.36
        ///169.64 -43.6
        ///169.13 -43.84
        ///168.77 -44.02
        ///168.49 -44.16
        ///167.37 -44.65
        ///167.1 -44.82
        ///166.77 -45.06
        ///166.44 -45.31
        ///166.05 -45.59        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUS_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("AUS_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///102.875 -6.795
        ///101.669 -6.345
        ///100.038 -4.495
        ///98.051 -1.79
        ///95.745 1.458
        ///93.435 4.526
        ///92.508 6.271
        ///92.508 6.271
        ///93.68 6.972
        ///93.873 7.105
        ///93.873 7.105
        ///94.441 7.447
        ///94.182 7.897
        ///93.979 8.424
        ///93.869 8.744
        ///93.813 9.045
        ///94.07 9.119
        ///93.951 9.513
        ///93.83 9.947
        ///93.771 10.383
        ///94.104 10.452
        ///94.068 10.801
        ///94.549 10.847
        ///94.604 31.855
        ///96.255 29.19
        ///96.913 26.021
        ///96.086 22.398
        ///96.192 19.997
        ///96.841 17.062
        ///97.368 13.614
        ///97.368 13.614
        ///97.164 13.239
        ///96.66 11.526
        ///96.61 9.269
        ///96.846 6.756 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSS_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("BSS_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///91.642 9.417
        ///92.064 7.1
        ///93.435 4.526
        ///95.745 1.458
        ///98.051 -1.79
        ///100.038 -4.495
        ///101.669 -6.345
        ///104.18 -7.277
        ///104.933 -7.622
        ///104.933 -7.622
        ///103.229 -8.937
        ///100.256 -10.784
        ///99.044 -11.72
        ///97.977 -13.236
        ///96.63 -15.594
        ///95.057 -17.616
        ///92.53 -21.098
        ///90.902 -22.895
        ///87.982 -26.208
        ///86.41 -28.735
        ///85.455 -30.026
        ///83.433 -32.216
        ///82.647 -33.339
        ///80.909 -35.22
        ///78.453 -36.991
        ///78.453 -36.991
        ///78.419 -36.96
        ///79.32 -36.122
        ///78.321 -35.422
        ///78.458 -35.189
        ///77.001 -34.267
        ///78.035 -33.183
        ///76.208 -3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CAP_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("CAP_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-81.668 18.739
        ///-79.378 19.073
        ///-76.718 19.408
        ///-73.96 19.699
        ///-70.499 19.832
        ///-67.652 19.884
        ///-64.49 19.757
        ///-61.238 19.584
        ///-61.238 19.584
        ///-59.196 17.66
        ///-58.356 15.848
        ///-57.655 14.925
        ///-57.282 13.071
        ///-57.636 11.222
        ///-57.788 10.695
        ///-57.788 10.695
        ///-69.923 11.541
        ///-75.05 12.207
        ///-75.05 12.207
        ///-75.886 11.352
        ///-77.419 9.287
        ///-78.434 7.938
        ///-78.426 6.728
        ///-78.426 6.728
        ///-78.41 6.716
        ///-78.295 6.47
        ///-78.196 6.341
        ///-78.044 6.04
        ///-77.974 5.82
        ///-77.922 5.574
        ///-77.924 5.374
        ///-77.926 5.173
        ///-77.954 5.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CAR_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("CAR_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///119.299 1.209
        ///119.307 2.018
        ///118.557 3.505
        ///119.404 5.131
        ///119.426 5.422
        ///119.426 5.422
        ///120.857 6.534
        ///122.056 7.927
        ///123.093 8.394
        ///123.093 8.394
        ///123.404 8.091
        ///123.584 7.889
        ///123.584 7.889
        ///123.599 7.787
        ///123.959 6.132
        ///125.016 5.164
        ///125.857 4.517
        ///126.174 3.994
        ///126.174 3.994
        ///125.88 2.978
        ///125.763 1.836
        ///125.763 1.836
        ///125.717 1.832
        ///122.884 1.499
        ///120.904 1.488
        ///119.621 1.345
        ///119.299 1.209
        ///.
        /// </summary>
        internal static string CEL_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("CEL_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-104.807 18.807
        ///-104.737 18.758
        ///-104.111 18.424
        ///-103.53 17.985
        ///-102.9 17.6
        ///-102.1 17.2
        ///-101.4 16.9
        ///-100.7 16.6
        ///-99.9 16.3
        ///-99.4 16.1
        ///-98.877 15.839
        ///-98.877 15.839
        ///-97.41 15.322
        ///-96.037 15.13
        ///-96.037 15.13
        ///-94.834 14.5
        ///-91.58 12.892
        ///-89.232 11.869
        ///-87.788 10.668
        ///-85.747 9.374
        ///-82.757 7.684
        ///-82.757 7.684
        ///-82.823 3.12
        ///-82.823 3.12
        ///-83.376 3.164
        ///-84.469 3.114
        ///-84.565 2.532
        ///-84.576 1.6
        ///-85.347 1.642
        ///-85.386 0.832
        ///-90.665 1.125
        ///-90.695 1.738
        ///-91.558 1.815
        ///-91.536 2.011
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COC_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("COC_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///20.091 43.826
        ///20.148 43.875
        ///23.304 45.057
        ///24.622 45.539
        ///25.774 45.651
        ///25.774 45.651
        ///22.264 43.064
        ///22.245 41.926
        ///23.398 40.678
        ///23.398 40.678
        ///22.879 40.676
        ///21.414 42.143
        ///20.091 43.826
        ///.
        /// </summary>
        internal static string EAW_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("EAW_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///127.862 3.363
        ///127.659 2.97
        ///127.659 2.97
        ///127.195 3.464
        ///126.304 4.285
        ///126.288 4.388
        ///126.288 4.388
        ///126.174 3.994
        ///126.174 3.994
        ///125.857 4.517
        ///125.016 5.164
        ///123.959 6.132
        ///123.599 7.787
        ///123.584 7.889
        ///123.584 7.889
        ///123.404 8.091
        ///122.639 8.835
        ///122.168 9.713
        ///122.102 10.651
        ///121.736 11.734
        ///121.346 12.879
        ///120.777 13.207
        ///120.0 13.652
        ///119.542 15.101
        ///119.49 17.28
        ///120.36 18.697
        ///120.427 20.837
        ///120.967 23.308
        ///120.967 23.308
        ///121.237 23.273
        ///122.069 23.25
        ///122.069 23.25
        ///122.062 23.091
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EPH_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("EPH_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///142.981 24.586
        ///142.483 24.49
        ///141.899 24.245
        ///141.708 24.236
        ///141.708 24.236
        ///141.09 25.228
        ///141.09 25.228
        ///140.226 25.069
        ///139.262 24.85
        ///139.262 24.85
        ///138.473 26.917
        ///137.854 28.511
        ///137.028 30.806
        ///136.65 31.939
        ///136.553 31.946
        ///136.366 32.415
        ///136.366 32.415
        ///136.516 32.481
        ///138.531 33.753
        ///139.238 34.205
        ///139.849 34.604
        ///141.164 34.938
        ///141.702 35.111
        ///141.928 35.16
        ///141.971 35.212
        ///141.971 35.212
        ///142.0 35.0
        ///142.0 34.0
        ///142.0 33.0
        ///142.2 31.0
        ///142.5 30.0
        ///142.8 29.0
        ///143.2 28.0
        ///143.2 27. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ESB_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("ESB_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///67.253 26.0
        ///67.241 25.661
        ///67.109 25.539
        ///66.839 25.208
        ///66.839 25.208
        ///66.375 25.208
        ///64.036 25.082
        ///61.709 25.729
        ///59.923 26.501
        ///57.385 27.628
        ///54.319 29.152
        ///52.485 30.84
        ///50.851 32.135
        ///47.911 33.625
        ///45.401 35.523
        ///43.756 36.276
        ///42.536 36.689
        ///41.157 37.059
        ///39.681 37.311
        ///38.92 37.293
        ///37.94 37.138
        ///37.179 36.633
        ///36.404 36.003
        ///35.873 36.355
        ///35.873 36.355
        ///35.873 36.355
        ///35.873 36.355
        ///35.83 36.382
        ///35.542 36.349
        ///35.542 36.349
        ///34.736 35.815
        ///32.571 35.726
        ///30.829 35.943
        ///26.284 36.9
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EUR_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("EUR_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-102.171 2.988
        ///-101.898 2.999
        ///-101.499 2.606
        ///-101.203 2.24
        ///-101.196 2.199
        ///-101.194 2.199
        ///-101.194 2.199
        ///-101.196 2.197
        ///-101.149 1.98
        ///-101.049 1.906
        ///-100.974 1.832
        ///-100.908 1.744
        ///-100.973 1.679
        ///-100.964 1.655
        ///-101.074 1.514
        ///-101.047 1.471
        ///-101.153 1.386
        ///-101.195 1.423
        ///-101.315 1.35
        ///-101.348 1.399
        ///-101.423 1.338
        ///-101.487 1.389
        ///-101.58 1.318
        ///-101.644 1.404
        ///-101.825 1.334
        ///-101.959 1.269
        ///-102.082 1.206
        ///-102.183 1.138
        ///-102.183 1.138
        ///-102.183 1.138
        ///-102.223 1.214
        ///-102.203 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GAL_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("GAL_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///67.146 -1.943
        ///67.302 -1.708
        ///66.647 -1.245
        ///66.799 -1.031
        ///66.462 -0.698
        ///66.731 -0.32
        ///66.248 0.127
        ///66.427 0.419
        ///66.079 0.681
        ///66.537 1.432
        ///64.961 2.496
        ///64.826 2.267
        ///63.426 2.762
        ///62.207 3.494
        ///60.576 5.05
        ///59.492 5.911
        ///59.587 6.104
        ///58.515 7.114
        ///57.636 7.702
        ///56.337 8.983
        ///56.337 8.983
        ///59.686 11.232
        ///59.007 11.946
        ///58.3 12.7
        ///58.159 12.841
        ///58.159 12.841
        ///58.785 13.609
        ///59.9 15.5
        ///61.209 17.302
        ///62.643 19.478
        ///64.122 21.888
        ///65.511 23.68
        ///66.552 24.854
        ///67.109 25.539
        ///67.241 25.661
        ///67. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IND_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("IND_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-125.172 40.346
        ///-125.45 40.354
        ///-126.159 40.39
        ///-126.869 40.422
        ///-127.579 40.45
        ///-127.579 40.539
        ///-127.717 40.573
        ///-127.639 41.081
        ///-127.56 41.589
        ///-127.446 41.555
        ///-127.401 41.641
        ///-127.241 41.692
        ///-127.039 42.357
        ///-126.627 43.014
        ///-127.571 43.42
        ///-128.528 43.818
        ///-129.498 44.208
        ///-130.48 44.589
        ///-130.367 44.93
        ///-130.069 45.285
        ///-130.187 45.414
        ///-129.936 45.736
        ///-129.869 45.896
        ///-130.073 45.943
        ///-130.051 46.196
        ///-129.917 46.229
        ///-129.803 46.433
        ///-129.572 46.402
        ///-129.259 47.065
        ///-128.938 47.727        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JDF_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("JDF_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-112.023 -31.536
        ///-111.66 -31.556
        ///-111.202 -31.564
        ///-110.687 -31.715
        ///-110.21 -31.92
        ///-109.791 -32.115
        ///-109.435 -32.4
        ///-109.206 -32.661
        ///-108.972 -32.936
        ///-109.183 -33.02
        ///-109.41 -33.14
        ///-109.323 -33.392
        ///-109.205 -33.702
        ///-109.27 -33.917
        ///-109.277 -34.204
        ///-109.255 -34.545
        ///-109.259 -34.545
        ///-109.691 -34.609
        ///-109.919 -34.702
        ///-110.141 -34.817
        ///-110.326 -34.946
        ///-110.527 -35.061
        ///-110.795 -35.092
        ///-110.795 -35.092
        ///-110.827 -35.091
        ///-111.133 -34.993
        ///-111.369 -34.921
        ///-111.4 -34.912
        ///-111.756  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JFD_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("JFD_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///158.83 59.965
        ///160.358 58.672
        ///162.469 57.031
        ///163.383 55.891
        ///164.074 55.194
        ///164.074 55.194
        ///164.074 55.194
        ///164.074 55.194
        ///164.074 55.194
        ///164.074 55.194
        ///167.084 53.848
        ///169.118 53.1
        ///169.118 53.1
        ///168.312 53.12
        ///163.486 52.733
        ///161.475 52.5
        ///161.475 52.5
        ///161.18 52.196
        ///160.324 51.291
        ///159.354 50.485
        ///156.41 48.61
        ///156.129 48.368
        ///156.129 48.368
        ///155.897 49.148
        ///155.495 51.451
        ///155.027 53.186
        ///154.776 55.19
        ///155.002 57.033
        ///156.658 58.511
        ///157.959 59.54
        ///158.83 59.965
        ///.
        /// </summary>
        internal static string KAM_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("KAM_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///142.558 11.315
        ///143.221 12.787
        ///144.307 14.549
        ///145.209 16.686
        ///145.392 16.826
        ///145.197 17.85
        ///145.357 17.919
        ///145.167 18.534
        ///144.991 19.045
        ///144.8 18.959
        ///144.373 19.798
        ///144.258 19.758
        ///144.106 19.989
        ///142.759 22.509
        ///141.708 24.236
        ///141.708 24.236
        ///141.899 24.245
        ///142.483 24.49
        ///143.193 24.626
        ///143.37 24.632
        ///143.37 24.632
        ///144.0 24.0
        ///145.0 23.0
        ///146.2 22.0
        ///147.0 21.0
        ///147.3 20.0
        ///147.3 18.8
        ///147.3 17.5
        ///147.3 15.6
        ///146.6 13.9
        ///144.8 12.3
        ///142.558 11.315
        ///.
        /// </summary>
        internal static string MAR_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("MAR_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///92.508 6.271
        ///92.064 7.1
        ///91.45 10.462
        ///91.45 10.462
        ///92.695 14.711
        ///93.492 17.605
        ///94.182 19.788
        ///94.67 21.654
        ///95.407 23.626
        ///96.679 25.015
        ///96.679 25.015
        ///96.086 22.398
        ///96.192 19.997
        ///96.841 17.062
        ///97.398 13.414
        ///94.549 10.847
        ///94.068 10.801
        ///94.104 10.452
        ///93.771 10.383
        ///93.83 9.947
        ///93.951 9.513
        ///94.07 9.119
        ///93.813 9.045
        ///93.869 8.744
        ///93.979 8.424
        ///94.182 7.897
        ///94.441 7.447
        ///93.873 7.105
        ///93.873 7.105
        ///93.68 6.972
        ///92.508 6.271
        ///.
        /// </summary>
        internal static string MAW_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("MAW_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///126.329 -0.987
        ///126.002 -0.326
        ///125.734 0.51
        ///125.74 1.608
        ///125.88 2.978
        ///126.288 4.388
        ///126.288 4.388
        ///126.304 4.285
        ///127.195 3.464
        ///127.659 2.97
        ///127.659 2.97
        ///127.396 2.46
        ///127.046 1.147
        ///126.873 0.055
        ///126.919 -1.029
        ///126.919 -1.029
        ///126.329 -0.987
        ///.
        /// </summary>
        internal static string MOL_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("MOL_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-180.0 50.45
        ///-180.0 90.0
        ///180.0 90.0
        ///180.0 50.45
        ///178.47 50.559
        ///175.474 50.938
        ///171.544 52.126
        ///167.084 53.848
        ///164.074 55.194
        ///164.074 55.194
        ///163.383 55.891
        ///162.469 57.031
        ///160.358 58.672
        ///158.83 59.965
        ///158.83 59.965
        ///157.959 59.54
        ///156.658 58.511
        ///155.002 57.033
        ///154.776 55.19
        ///155.027 53.186
        ///155.495 51.451
        ///155.897 49.148
        ///156.129 48.368
        ///156.129 48.368
        ///155.119 47.473
        ///154.469 46.797
        ///152.565 45.505
        ///150.939 44.809
        ///149.546 44.024
        ///148.087 43.23
        ///146.023 42.087
        ///144.904 41.531
        ///144.229  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NAM_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("NAM_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-78.662 3.834
        ///-78.834 3.577
        ///-79.064 3.369
        ///-79.331 3.043
        ///-79.608 2.662
        ///-79.857 2.317
        ///-80.004 2.108
        ///-80.208 1.772
        ///-80.43 1.427
        ///-80.607 1.017
        ///-80.756 0.698
        ///-80.887 0.343
        ///-81.074 -0.104
        ///-81.195 -0.386
        ///-81.289 -0.733
        ///-81.402 -1.125
        ///-81.423 -1.372
        ///-81.462 -1.582
        ///-81.511 -1.957
        ///-81.56 -2.24
        ///-81.58 -2.496
        ///-81.611 -2.779
        ///-81.963 -5.714
        ///-80.556 -9.316
        ///-77.828 -13.647
        ///-74.772 -16.64
        ///-73.855 -17.064
        ///-72.183 -18.703
        ///-71.604 -19.532
        ///-71.273 -20.375
        ///-71.253 -21.059
        ///-71.063 -21.927        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NAZ_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("NAZ_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///127.132 -6.738
        ///126.417 -6.345
        ///125.397 -5.787
        ///123.552 -4.389
        ///122.056 -3.345
        ///122.056 -3.345
        ///124.077 -3.361
        ///126.689 -2.696
        ///128.81 -2.491
        ///130.486 -2.681
        ///131.702 -3.083
        ///132.3 -3.841
        ///132.3 -3.841
        ///129.125 -5.519
        ///129.222 -5.677
        ///127.132 -6.738
        ///.
        /// </summary>
        internal static string NBS_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("NBS_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///134.641 6.977
        ///134.71 6.971
        ///136.669 7.256
        ///137.347 7.649
        ///137.856 8.258
        ///138.289 9.039
        ///138.289 9.039
        ///144.797 6.123
        ///146.097 6.123
        ///146.097 6.123
        ///148.676 3.274
        ///148.726 1.414
        ///149.145 0.43
        ///149.305 -0.642
        ///149.305 -0.642
        ///147.476 -0.311
        ///145.909 -0.397
        ///144.427 -0.798
        ///143.796 -0.722
        ///142.877 -1.008
        ///141.696 -1.445
        ///140.823 -1.34
        ///140.083 -1.648
        ///139.727 -1.926
        ///139.727 -1.926
        ///139.001 -1.675
        ///138.315 -1.447
        ///137.572 -1.19
        ///136.972 -1.018
        ///136.867 -0.978
        ///136.867 -0.978
        ///134.839 -0.719
        ///132.749 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NCA_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("NCA_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///176.631 -19.541
        ///175.95 -19.934
        ///171.028 -21.856
        ///170.556 -21.94
        ///170.556 -21.94
        ///170.274 -21.683
        ///169.536 -21.383
        ///168.556 -20.244
        ///167.594 -18.34
        ///166.653 -16.28
        ///165.889 -13.684
        ///165.294 -11.694
        ///165.294 -11.694
        ///166.056 -11.538
        ///166.939 -11.201
        ///167.948 -11.01
        ///168.869 -10.769
        ///168.869 -10.769
        ///169.077 -10.892
        ///170.215 -11.501
        ///171.26 -12.301
        ///172.591 -13.123
        ///173.977 -14.149
        ///174.569 -15.371
        ///175.232 -16.667
        ///175.68 -17.256
        ///175.903 -17.963
        ///176.39 -18.967
        ///176.631 -19.541
        ///.
        /// </summary>
        internal static string NHF_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("NHF_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///152.124 -3.647
        ///152.58 -4.051
        ///153.662 -5.818
        ///153.662 -5.818
        ///153.187 -5.772
        ///152.571 -5.653
        ///151.912 -5.919
        ///151.57 -6.175
        ///151.049 -6.513
        ///150.315 -6.828
        ///149.388 -7.03
        ///149.222 -7.147
        ///149.222 -7.147
        ///148.614 -6.795
        ///147.933 -6.228
        ///146.602 -5.39
        ///145.277 -4.276
        ///144.21 -3.549
        ///144.2 -3.546
        ///144.2 -3.546
        ///144.368 -3.531
        ///144.807 -3.55
        ///145.399 -3.485
        ///146.11 -3.471
        ///146.415 -3.438
        ///146.836 -3.755
        ///146.918 -3.641
        ///146.999 -3.514
        ///147.083 -3.385
        ///147.162 -3.261
        ///147.241 -3.152
        ///147.325 -3.053
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NNB_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("NNB_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///119.299 1.209
        ///119.621 1.345
        ///120.904 1.488
        ///122.884 1.499
        ///125.717 1.832
        ///125.763 1.836
        ///125.763 1.836
        ///125.74 1.608
        ///125.734 0.51
        ///126.002 -0.326
        ///126.329 -0.987
        ///126.329 -0.987
        ///128.592 -1.147
        ///129.92 -1.022
        ///129.92 -1.022
        ///129.396 -1.375
        ///127.459 -2.513
        ///127.459 -2.513
        ///127.938 -2.576
        ///127.938 -2.576
        ///126.689 -2.696
        ///124.077 -3.361
        ///122.056 -3.345
        ///122.056 -3.345
        ///121.841 -3.194
        ///120.167 -2.052
        ///120.167 -2.052
        ///119.294 0.637
        ///119.299 1.209
        ///.
        /// </summary>
        internal static string NSU_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("NSU_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///43.7 11.9
        ///42.437 11.574
        ///41.418 11.384
        ///41.418 11.384
        ///40.784 10.095
        ///39.497 8.724
        ///38.07 6.93
        ///37.593 5.957
        ///36.926 5.954
        ///36.294 5.032
        ///32.194 5.689
        ///31.287 4.462
        ///30.515 4.205
        ///30.457 2.819
        ///31.553 2.528
        ///31.62 2.497
        ///30.605 1.422
        ///29.876 0.062
        ///29.393 -1.313
        ///28.867 -2.323
        ///28.951 -3.966
        ///29.6 -5.099
        ///29.594 -6.078
        ///30.495 -7.488
        ///31.612 -7.775
        ///32.636 -8.544
        ///33.562 -8.748
        ///34.074 -10.438
        ///34.708 -11.04
        ///34.174 -12.409
        ///34.071 -13.178
        ///34.848 -14.545
        ///34.605 -15.851
        ///35.191 -16.848
        ///35.202 - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NUB_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("NUB_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///151.559 -7.922
        ///151.68 -7.955
        ///152.062 -8.104
        ///152.411 -8.26
        ///152.685 -8.388
        ///152.959 -8.544
        ///153.108 -8.684
        ///153.17 -8.783
        ///153.237 -8.89
        ///153.254 -9.172
        ///153.254 -9.172
        ///153.687 -8.976
        ///155.478 -7.489
        ///155.478 -7.489
        ///156.524 -8.47
        ///156.524 -8.47
        ///156.442 -9.164
        ///156.283 -9.215
        ///156.08 -9.259
        ///156.09 -9.518
        ///155.9 -9.561
        ///155.843 -9.492
        ///155.651 -9.561
        ///155.614 -9.501
        ///155.488 -9.553
        ///155.469 -9.483
        ///155.16 -9.619
        ///155.197 -9.716
        ///155.074 -9.796
        ///154.845 -9.832
        ///154.843 -9.724
        ///154.218 -9.909
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NWB_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("NWB_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///180.0 -37.4573
        ///180.0 -67.3697
        ///172.5977 -69.6632
        ///172.5977 -69.6632
        ///171.667 -69.3137
        ///169.967 -68.4756
        ///160.1242 -61.9586
        ///160.1242 -61.9586
        ///160.8019 -61.805
        ///160.8019 -61.805
        ///160.848 -61.5207
        ///160.183 -60.2584
        ///160.004 -60.0796
        ///159.729 -59.7375
        ///159.109 -59.517
        ///158.48 -59.1646
        ///158.069 -58.8131
        ///157.693 -58.3722
        ///157.564 -58.0461
        ///157.481 -57.7121
        ///157.489 -57.4534
        ///157.442 -57.2619
        ///157.46 -57.2126
        ///157.578 -57.1038
        ///157.732 -56.8904
        ///157.804 -56.6408
        ///157.866 -56.4299
        ///157.865 -56.2481
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PAC_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("PAC_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///118.742 6.825
        ///117.196 8.943
        ///117.196 8.943
        ///118.137 10.15
        ///119.694 12.484
        ///120.043 13.535
        ///120.101 13.594
        ///120.101 13.594
        ///120.777 13.207
        ///121.346 12.879
        ///121.736 11.734
        ///122.061 10.773
        ///122.061 10.773
        ///118.742 6.825
        ///.
        /// </summary>
        internal static string PAL_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("PAL_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///12.757 47.432
        ///15.321 47.495
        ///16.752 48.126
        ///17.819 48.837
        ///19.038 49.175
        ///21.133 49.471
        ///25.899 48.068
        ///25.899 48.068
        ///22.346 47.88
        ///20.613 47.242
        ///15.469 45.973
        ///15.242 45.907
        ///15.242 45.907
        ///12.989 47.121
        ///12.757 47.432
        ///.
        /// </summary>
        internal static string PES_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("PES_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Plate identifications for Matthews et al. 2016 Present Day Model	
        ///!		
        ///PlateID	Code	Description
        ///101	NAM	North America Plate
        ///201	SAM	South America Plate
        ///224	CAR	Caribbean Plate
        ///301	EUR	Northern European Craton
        ///328	EAW	Eastern Dinaride Accretionary Wedge
        ///334	PES	Pelso
        ///337	TIS	Tisza
        ///340	SPN	Southern Panonian
        ///406	KAM	Kamchatka Peninsula
        ///501	IND	Southern India Craton
        ///503	ARB	Arabia
        ///566	SSU	Southeast Sulawesi
        ///511	CAP	Capricorn Plate
        ///607	MAW	Mawgyi (Central Argoland)
        ///608	SPS	South Philippine Sea
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlateIDs_Matthews2016_Earthbyte {
            get {
                return ResourceManager.GetString("PlateIDs_Matthews2016_Earthbyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-105.402 17.868
        ///-106.308 17.929
        ///-106.318 18.016
        ///-106.311 18.12
        ///-106.281 18.282
        ///-106.244 18.52
        ///-106.527 18.544
        ///-106.755 18.59
        ///-107.002 18.647
        ///-107.213 18.733
        ///-107.273 18.756
        ///-107.523 18.863
        ///-107.816 18.936
        ///-108.233 19.108
        ///-108.198 19.224
        ///-108.535 19.384
        ///-108.896 19.55
        ///-108.903 19.625
        ///-109.16 19.807
        ///-109.45 20.028
        ///-109.373 20.142
        ///-109.378 20.175
        ///-109.319 20.243
        ///-109.215 20.397
        ///-109.187 20.5
        ///-109.285 20.559
        ///-109.261 20.642
        ///-109.194 20.739
        ///-109.111 20.824
        ///-108.915 21.068
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RIV_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("RIV_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-75.05 12.207
        ///-69.923 11.541
        ///-57.788 10.695
        ///-57.788 10.695
        ///-57.636 11.222
        ///-57.282 13.071
        ///-57.655 14.925
        ///-58.356 15.848
        ///-59.196 17.66
        ///-60.741 19.121
        ///-60.741 19.121
        ///-60.33 19.181
        ///-57.872 18.723
        ///-55.713 17.846
        ///-52.84 16.777
        ///-50.878 16.215
        ///-48.872 16.06
        ///-46.831 15.625
        ///-46.831 15.625
        ///-46.87 15.448
        ///-46.899 15.344
        ///-46.899 15.344
        ///-46.864 15.339
        ///-45.027 14.942
        ///-44.936 12.544
        ///-44.145 12.487
        ///-44.138 12.056
        ///-43.764 12.029
        ///-43.787 10.908
        ///-40.972 10.67
        ///-40.971 9.881
        ///-40.738 9.879        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAM_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SAM_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-25.951 -60.395
        ///-26.014 -60.384
        ///-27.698 -60.624
        ///-27.698 -60.624
        ///-27.697 -60.617
        ///-27.705 -60.467
        ///-28.677 -60.459
        ///-29.598 -60.435
        ///-29.881 -60.174
        ///-30.031 -59.937
        ///-30.108 -59.515
        ///-29.555 -59.514
        ///-29.563 -58.817
        ///-29.951 -58.805
        ///-30.007 -58.272
        ///-29.844 -58.262
        ///-29.852 -57.598
        ///-30.069 -57.6
        ///-30.134 -57.095
        ///-30.134 -57.095
        ///-30.38 -57.094
        ///-30.469 -56.851
        ///-30.743 -56.859
        ///-30.743 -56.57
        ///-30.727 -56.511
        ///-30.721 -56.449
        ///-30.378 -56.443
        ///-30.334 -56.29
        ///-30.325 -56.134
        ///-30.332 -56.05 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAN_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SAN_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///129.026 -7.775
        ///129.005 -7.758
        ///127.132 -6.738
        ///127.132 -6.738
        ///129.222 -5.677
        ///129.125 -5.519
        ///132.3 -3.841
        ///132.3 -3.841
        ///132.455 -4.037
        ///132.455 -4.037
        ///132.304 -5.598
        ///131.535 -6.457
        ///130.477 -7.356
        ///129.026 -7.775
        ///.
        /// </summary>
        internal static string SBA_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SBA_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-76.257 -51.761
        ///-74.99 -52.556
        ///-73.625 -53.058
        ///-71.788 -53.872
        ///-69.632 -54.39
        ///-67.987 -54.55
        ///-65.699 -54.54
        ///-64.101 -54.305
        ///-61.813 -53.72
        ///-60.519 -53.632
        ///-59.031 -53.623
        ///-57.194 -53.607
        ///-55.146 -53.525
        ///-54.018 -53.199
        ///-51.942 -52.728
        ///-50.218 -52.65
        ///-48.82 -52.769
        ///-47.863 -52.643
        ///-46.609 -52.66
        ///-45.398 -52.793
        ///-43.724 -53.045
        ///-41.944 -53.054
        ///-40.276 -53.347
        ///-39.201 -53.308
        ///-37.64 -53.195
        ///-35.979 -53.477
        ///-35.0 -54.151
        ///-33.972 -54.379
        ///-31.875 -54.81
        ///-29.737 -54.869
        ///-29. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SCO_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SCO_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///144.2 -3.546
        ///142.962 -3.118
        ///141.94 -2.732
        ///140.944 -2.247
        ///139.829 -1.961
        ///139.727 -1.926
        ///139.727 -1.926
        ///140.083 -1.648
        ///140.823 -1.34
        ///141.696 -1.445
        ///142.877 -1.008
        ///143.796 -0.722
        ///144.427 -0.798
        ///145.909 -0.397
        ///147.476 -0.311
        ///149.317 -0.644
        ///149.317 -0.644
        ///149.332 -0.744
        ///149.332 -0.744
        ///149.481 -0.818
        ///149.769 -1.005
        ///150.023 -1.021
        ///150.344 -1.123
        ///150.717 -1.224
        ///151.089 -1.308
        ///151.427 -1.46
        ///151.816 -1.646
        ///152.155 -1.865
        ///152.578 -2.134
        ///152.916 -2.15
        ///153.119 -2.2
        ///153.39 -2.436        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SNB_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SNB_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///149.999 -7.62
        ///149.545 -7.333
        ///149.222 -7.147
        ///149.222 -7.147
        ///149.388 -7.03
        ///150.315 -6.828
        ///151.049 -6.513
        ///151.57 -6.175
        ///151.912 -5.919
        ///152.571 -5.653
        ///153.187 -5.772
        ///153.662 -5.818
        ///153.662 -5.818
        ///153.93 -6.254
        ///154.721 -6.839
        ///154.721 -6.839
        ///154.73 -6.858
        ///154.778 -6.965
        ///154.778 -6.965
        ///155.039 -7.075
        ///155.478 -7.489
        ///155.478 -7.489
        ///153.687 -8.976
        ///153.254 -9.172
        ///153.254 -9.172
        ///153.237 -8.89
        ///153.17 -8.783
        ///153.108 -8.684
        ///152.959 -8.544
        ///152.685 -8.388
        ///152.411 -8.26
        ///152.062 -8.104 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOL_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SOL_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///41.418 11.384
        ///42.437 11.574
        ///43.7 11.9
        ///46.3 12.2
        ///46.5 12.5
        ///48.2 12.6
        ///48.8 13.0
        ///49.8 13.1
        ///50.2 13.4
        ///51.2 13.1
        ///52.2 14.6
        ///52.8 14.4
        ///53.0 14.6
        ///53.8 14.3
        ///54.5 15.2
        ///56.1 14.3
        ///56.3 14.5
        ///57.5 13.5
        ///58.3 12.7
        ///59.007 11.946
        ///59.686 11.232
        ///56.337 8.983
        ///56.337 8.983
        ///57.636 7.702
        ///58.515 7.114
        ///59.587 6.104
        ///59.492 5.911
        ///60.576 5.05
        ///62.207 3.494
        ///63.426 2.762
        ///64.826 2.267
        ///64.961 2.496
        ///66.537 1.432
        ///66.079 0.681
        ///66.427 0.419
        ///66.248 0.127
        ///66.731 -0.32
        ///66.462 -0.698
        ///66.799 -1.031
        ///66 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SOM_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SOM_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///18.378 44.788
        ///18.502 44.854
        ///22.832 45.988
        ///24.955 46.725
        ///25.669 47.446
        ///25.669 47.446
        ///26.145 45.688
        ///26.145 45.688
        ///26.093 45.679
        ///24.622 45.539
        ///23.304 45.057
        ///20.148 43.875
        ///20.091 43.826
        ///20.091 43.826
        ///20.067 43.856
        ///18.378 44.788
        ///.
        /// </summary>
        internal static string SPN_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SPN_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///132.031 29.967
        ///133.012 30.361
        ///134.058 31.205
        ///134.941 31.77
        ///136.366 32.415
        ///136.366 32.415
        ///136.553 31.946
        ///136.65 31.939
        ///137.028 30.806
        ///137.854 28.511
        ///138.473 26.917
        ///139.262 24.85
        ///139.262 24.85
        ///140.226 25.069
        ///141.09 25.228
        ///141.09 25.228
        ///142.759 22.509
        ///144.106 19.989
        ///144.258 19.758
        ///144.373 19.798
        ///144.8 18.959
        ///144.991 19.045
        ///145.167 18.534
        ///145.357 17.919
        ///145.197 17.85
        ///145.392 16.826
        ///145.209 16.686
        ///144.307 14.549
        ///143.221 12.787
        ///142.558 11.315
        ///142.558 11.315
        ///142.3 11.2
        ///140 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SPS_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SPS_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///120.167 -2.052
        ///121.841 -3.194
        ///123.552 -4.389
        ///125.397 -5.787
        ///126.417 -6.345
        ///129.005 -7.758
        ///129.026 -7.775
        ///129.026 -7.775
        ///128.915 -7.807
        ///125.416 -8.526
        ///122.361 -9.281
        ///121.313 -9.295
        ///121.313 -9.295
        ///121.267 -8.277
        ///121.013 -7.075
        ///120.69 -5.216
        ///120.521 -3.142
        ///120.167 -2.052
        ///.
        /// </summary>
        internal static string SSU_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SSU_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///123.093 8.394
        ///122.056 7.927
        ///120.857 6.534
        ///119.569 5.533
        ///119.569 5.533
        ///118.959 6.525
        ///118.742 6.825
        ///118.742 6.825
        ///122.061 10.773
        ///122.061 10.773
        ///122.102 10.651
        ///122.168 9.713
        ///122.639 8.835
        ///123.093 8.394
        ///.
        /// </summary>
        internal static string SUL_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("SUL_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///15.242 45.907
        ///15.469 45.973
        ///20.613 47.242
        ///22.346 47.88
        ///25.899 48.068
        ///25.899 48.068
        ///25.669 47.446
        ///25.669 47.446
        ///24.955 46.725
        ///22.832 45.988
        ///18.502 44.854
        ///18.378 44.788
        ///18.378 44.788
        ///18.347 44.805
        ///15.287 45.881
        ///15.242 45.907
        ///.
        /// </summary>
        internal static string TIS_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("TIS_contourXY_Matthews2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !lon lat
        ///-177.289 -27.728
        ///-178.716 -27.614
        ///-178.585 -27.294
        ///-177.669 -24.775
        ///-177.379 -22.679
        ///-177.239 -22.28
        ///-176.738 -20.592
        ///-176.651 -20.468
        ///-176.799 -20.426
        ///-176.476 -19.391
        ///-176.75 -19.152
        ///-176.591 -17.807
        ///-176.975 -16.598
        ///-176.975 -16.598
        ///-175.409 -16.709
        ///-175.409 -16.709
        ///-175.331 -16.135
        ///-175.489 -16.046
        ///-175.372 -15.811
        ///-175.579 -15.789
        ///-175.491 -15.404
        ///-175.492 -14.84
        ///-175.402 -14.312
        ///-175.359 -14.153
        ///-175.24 -13.851
        ///-175.24 -13.851
        ///-174.715 -14.148
        ///-173.52 -14.695
        ///-172 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TON_contourXY_Matthews2016 {
            get {
                return ResourceManager.GetString("TON_contourXY_Matthews2016", resourceCulture);
            }
        }
    }
}
