//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYRIAM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PriestlyMcKenzey2013_T_model {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PriestlyMcKenzey2013_T_model() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MYRIAM.Properties.PriestlyMcKenzey2013_T_model", typeof(PriestlyMcKenzey2013_T_model).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.1663900e+03
        ///  -1.7700000e+02   8.9000000e+01   1.1679400e+03
        ///  -1.7500000e+02   8.9000000e+01   1.1662200e+03
        ///  -1.7300000e+02   8.9000000e+01   1.1672500e+03
        ///  -1.7100000e+02   8.9000000e+01   1.1691100e+03
        ///  -1.6900000e+02   8.9000000e+01   1.1739100e+03
        ///  -1.6700000e+02   8.9000000e+01   1.1744300e+03
        ///  -1.6500000e+02   8.9000000e+01   1.1760000e+03
        ///  -1.6300000e+02   8.9000000e+01   1.1750600e+03
        ///  -1.6100000e+02   8.9000000e+01   1.1756600e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH050km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH050km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.2448600e+03
        ///  -1.7700000e+02   8.9000000e+01   1.2435500e+03
        ///  -1.7500000e+02   8.9000000e+01   1.2443800e+03
        ///  -1.7300000e+02   8.9000000e+01   1.2436400e+03
        ///  -1.7100000e+02   8.9000000e+01   1.2422600e+03
        ///  -1.6900000e+02   8.9000000e+01   1.2462200e+03
        ///  -1.6700000e+02   8.9000000e+01   1.2452700e+03
        ///  -1.6500000e+02   8.9000000e+01   1.2457300e+03
        ///  -1.6300000e+02   8.9000000e+01   1.2447700e+03
        ///  -1.6100000e+02   8.9000000e+01   1.2450600e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH075km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH075km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.3194500e+03
        ///  -1.7700000e+02   8.9000000e+01   1.3173500e+03
        ///  -1.7500000e+02   8.9000000e+01   1.3189400e+03
        ///  -1.7300000e+02   8.9000000e+01   1.3177200e+03
        ///  -1.7100000e+02   8.9000000e+01   1.3158400e+03
        ///  -1.6900000e+02   8.9000000e+01   1.3170000e+03
        ///  -1.6700000e+02   8.9000000e+01   1.3155200e+03
        ///  -1.6500000e+02   8.9000000e+01   1.3152500e+03
        ///  -1.6300000e+02   8.9000000e+01   1.3143200e+03
        ///  -1.6100000e+02   8.9000000e+01   1.3146200e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH100km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH100km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.4555100e+03
        ///  -1.7700000e+02   8.9000000e+01   1.4535800e+03
        ///  -1.7500000e+02   8.9000000e+01   1.4549900e+03
        ///  -1.7300000e+02   8.9000000e+01   1.4532200e+03
        ///  -1.7100000e+02   8.9000000e+01   1.4512700e+03
        ///  -1.6900000e+02   8.9000000e+01   1.4510500e+03
        ///  -1.6700000e+02   8.9000000e+01   1.4496400e+03
        ///  -1.6500000e+02   8.9000000e+01   1.4493800e+03
        ///  -1.6300000e+02   8.9000000e+01   1.4481000e+03
        ///  -1.6100000e+02   8.9000000e+01   1.4483200e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH125km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH125km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.6304100e+03
        ///  -1.7700000e+02   8.9000000e+01   1.6292600e+03
        ///  -1.7500000e+02   8.9000000e+01   1.6310200e+03
        ///  -1.7300000e+02   8.9000000e+01   1.6290700e+03
        ///  -1.7100000e+02   8.9000000e+01   1.6273100e+03
        ///  -1.6900000e+02   8.9000000e+01   1.6270000e+03
        ///  -1.6700000e+02   8.9000000e+01   1.6261900e+03
        ///  -1.6500000e+02   8.9000000e+01   1.6261900e+03
        ///  -1.6300000e+02   8.9000000e+01   1.6252700e+03
        ///  -1.6100000e+02   8.9000000e+01   1.6254300e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH150km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH150km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.7076500e+03
        ///  -1.7700000e+02   8.9000000e+01   1.7076400e+03
        ///  -1.7500000e+02   8.9000000e+01   1.7077600e+03
        ///  -1.7300000e+02   8.9000000e+01   1.7078200e+03
        ///  -1.7100000e+02   8.9000000e+01   1.7076100e+03
        ///  -1.6900000e+02   8.9000000e+01   1.7076400e+03
        ///  -1.6700000e+02   8.9000000e+01   1.7077700e+03
        ///  -1.6500000e+02   8.9000000e+01   1.7076000e+03
        ///  -1.6300000e+02   8.9000000e+01   1.7078200e+03
        ///  -1.6100000e+02   8.9000000e+01   1.7075700e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH175km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH175km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.7419100e+03
        ///  -1.7700000e+02   8.9000000e+01   1.7420000e+03
        ///  -1.7500000e+02   8.9000000e+01   1.7420200e+03
        ///  -1.7300000e+02   8.9000000e+01   1.7419600e+03
        ///  -1.7100000e+02   8.9000000e+01   1.7419000e+03
        ///  -1.6900000e+02   8.9000000e+01   1.7420400e+03
        ///  -1.6700000e+02   8.9000000e+01   1.7420200e+03
        ///  -1.6500000e+02   8.9000000e+01   1.7420000e+03
        ///  -1.6300000e+02   8.9000000e+01   1.7419600e+03
        ///  -1.6100000e+02   8.9000000e+01   1.7420200e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH200km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH200km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.7670400e+03
        ///  -1.7700000e+02   8.9000000e+01   1.7679500e+03
        ///  -1.7500000e+02   8.9000000e+01   1.7682200e+03
        ///  -1.7300000e+02   8.9000000e+01   1.7682200e+03
        ///  -1.7100000e+02   8.9000000e+01   1.7682200e+03
        ///  -1.6900000e+02   8.9000000e+01   1.7682200e+03
        ///  -1.6700000e+02   8.9000000e+01   1.7682200e+03
        ///  -1.6500000e+02   8.9000000e+01   1.7682200e+03
        ///  -1.6300000e+02   8.9000000e+01   1.7682200e+03
        ///  -1.6100000e+02   8.9000000e+01   1.7682200e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH225km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH225km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.6931500e+03
        ///  -1.7700000e+02   8.9000000e+01   1.6942000e+03
        ///  -1.7500000e+02   8.9000000e+01   1.6956600e+03
        ///  -1.7300000e+02   8.9000000e+01   1.6959400e+03
        ///  -1.7100000e+02   8.9000000e+01   1.6961200e+03
        ///  -1.6900000e+02   8.9000000e+01   1.6978700e+03
        ///  -1.6700000e+02   8.9000000e+01   1.6988600e+03
        ///  -1.6500000e+02   8.9000000e+01   1.6992500e+03
        ///  -1.6300000e+02   8.9000000e+01   1.6989400e+03
        ///  -1.6100000e+02   8.9000000e+01   1.6992600e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH250km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH250km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.6381000e+03
        ///  -1.7700000e+02   8.9000000e+01   1.6390200e+03
        ///  -1.7500000e+02   8.9000000e+01   1.6398400e+03
        ///  -1.7300000e+02   8.9000000e+01   1.6405000e+03
        ///  -1.7100000e+02   8.9000000e+01   1.6403600e+03
        ///  -1.6900000e+02   8.9000000e+01   1.6409500e+03
        ///  -1.6700000e+02   8.9000000e+01   1.6420100e+03
        ///  -1.6500000e+02   8.9000000e+01   1.6422000e+03
        ///  -1.6300000e+02   8.9000000e+01   1.6423500e+03
        ///  -1.6100000e+02   8.9000000e+01   1.6421200e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH275km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH275km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.6436200e+03
        ///  -1.7700000e+02   8.9000000e+01   1.6447500e+03
        ///  -1.7500000e+02   8.9000000e+01   1.6451900e+03
        ///  -1.7300000e+02   8.9000000e+01   1.6453000e+03
        ///  -1.7100000e+02   8.9000000e+01   1.6450500e+03
        ///  -1.6900000e+02   8.9000000e+01   1.6452100e+03
        ///  -1.6700000e+02   8.9000000e+01   1.6456800e+03
        ///  -1.6500000e+02   8.9000000e+01   1.6456200e+03
        ///  -1.6300000e+02   8.9000000e+01   1.6453500e+03
        ///  -1.6100000e+02   8.9000000e+01   1.6452300e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH300km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH300km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.6422800e+03
        ///  -1.7700000e+02   8.9000000e+01   1.6426400e+03
        ///  -1.7500000e+02   8.9000000e+01   1.6427200e+03
        ///  -1.7300000e+02   8.9000000e+01   1.6424800e+03
        ///  -1.7100000e+02   8.9000000e+01   1.6423800e+03
        ///  -1.6900000e+02   8.9000000e+01   1.6415400e+03
        ///  -1.6700000e+02   8.9000000e+01   1.6415000e+03
        ///  -1.6500000e+02   8.9000000e+01   1.6415600e+03
        ///  -1.6300000e+02   8.9000000e+01   1.6409500e+03
        ///  -1.6100000e+02   8.9000000e+01   1.6407400e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH325km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH325km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.6399800e+03
        ///  -1.7700000e+02   8.9000000e+01   1.6407300e+03
        ///  -1.7500000e+02   8.9000000e+01   1.6408500e+03
        ///  -1.7300000e+02   8.9000000e+01   1.6407400e+03
        ///  -1.7100000e+02   8.9000000e+01   1.6401200e+03
        ///  -1.6900000e+02   8.9000000e+01   1.6396500e+03
        ///  -1.6700000e+02   8.9000000e+01   1.6397000e+03
        ///  -1.6500000e+02   8.9000000e+01   1.6398300e+03
        ///  -1.6300000e+02   8.9000000e+01   1.6399700e+03
        ///  -1.6100000e+02   8.9000000e+01   1.6399200e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH350km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH350km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.5591700e+03
        ///  -1.7700000e+02   8.9000000e+01   1.5595000e+03
        ///  -1.7500000e+02   8.9000000e+01   1.5595600e+03
        ///  -1.7300000e+02   8.9000000e+01   1.5588300e+03
        ///  -1.7100000e+02   8.9000000e+01   1.5575000e+03
        ///  -1.6900000e+02   8.9000000e+01   1.5574100e+03
        ///  -1.6700000e+02   8.9000000e+01   1.5570700e+03
        ///  -1.6500000e+02   8.9000000e+01   1.5569900e+03
        ///  -1.6300000e+02   8.9000000e+01   1.5572200e+03
        ///  -1.6100000e+02   8.9000000e+01   1.5570200e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH375km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH375km_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   -1.7900000e+02   8.9000000e+01   1.4353400e+03
        ///  -1.7700000e+02   8.9000000e+01   1.4348300e+03
        ///  -1.7500000e+02   8.9000000e+01   1.4346200e+03
        ///  -1.7300000e+02   8.9000000e+01   1.4344300e+03
        ///  -1.7100000e+02   8.9000000e+01   1.4335000e+03
        ///  -1.6900000e+02   8.9000000e+01   1.4338300e+03
        ///  -1.6700000e+02   8.9000000e+01   1.4329700e+03
        ///  -1.6500000e+02   8.9000000e+01   1.4331800e+03
        ///  -1.6300000e+02   8.9000000e+01   1.4329700e+03
        ///  -1.6100000e+02   8.9000000e+01   1.4330200e+03
        ///  -1.5900000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GRD_PM13_DEPTH400km_T {
            get {
                return ResourceManager.GetString("GRD_PM13_DEPTH400km_T", resourceCulture);
            }
        }
    }
}
